version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=paperclip-company-db
    ports:
      - '5432:5432'
    networks:
      - default
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: none

  postgres-init:
    image: postgres:15
    depends_on:
      postgres:
        condition: service_healthy
    environment:
        - PGPASSWORD=postgres
    volumes:
      - ./database/initialize-db.sh:/initialize-db.sh
      - ./database/schema.sql:/schema.sql
      - ./database/products.csv:/products.csv
    command: bash -c "sleep 10 && chmod u+x /initialize-db.sh && /initialize-db.sh"
